tools:
    jackhammer:
        material: DIAMOND_PICKAXE
    datawrench: 
        material: BONE
    sledgehammer:
        material: GOLD_PICKAXE
    paintbrush:
        material: SLIME_BALL
    duplicator:
        material: STONE_AXE