name: Multitool
version: 0.0.1-SNAPSHOT
main: com.theblockworlds.multitool.Multitool
author: ShiniOfTheGami
authors: [DukeVindzor, AceDexter]

commands:
   multitool:
     description: Manage MultiTool
     aliases: [mt, tools]
     usage: |
      USAGE:
      /multitool range - Toggles long range for tools
      /multitool list - Prints list of all tools available
      /multitool get <tool> - Gives you the specified tool

permissions:
   multitool.commands.*:
     description: Gives access to all MultiTool features
     children:
       multitool.togglerange: true
       multitool.list: true
       multitool.get.*: true
   multitool.command.get.*:
     description: Allows player to spawn all tools
     children:
       multitool.get.jackhammer: true
       multitool.get.paintbrush: true
       multitool.get.datawrench: true
       multitool.get.sledgehammer: true
       multitool.get.duplicator: true
   multitool.command.get.jackhammer:
     description: Allows player to spawn Jackhammer
     default: op
   multitool.command.get.paintbrush:
     description: Allows player to spawn Paint Brush
     default: op
   multitool.command.get.datawrench:
     description: Allows player to spawn Data Wrench
     default: op
   multitool.command.get.sledgehammer:
     description: Allows player to spawn Sledgehammer
     default: op
   multitool.command.get.duplicator:
     description: Allows player to spawn Duplicator
     default: op
   multitool.command.list:
     description: Prints list of all tools available
     default: op
   multitool.command.togglerange:
     description: Toggles long range for tools
     default: op